apps/cart/urls.py
from django.conf.urls import url
from cart.views import AddCartView, CartView, UpdateCartView,DelCartView

urlpatterns = [
    url(r'^$', CartView.as_view(), name='cart'), # 显示购物车页面
    url(r'^add$', AddCartView.as_view(), name='add'), # 添加购物车
    url(r'^update$', UpdateCartView.as_view(), name='update'), # 更新购物车页面
    url(r'^del$', DelCartView.as_view(), name='delete'), # 删除购物车中的商品
]

apps/goods/urls.py
from django.conf.urls import url
from goods.views import IndexView, DetailView, ListView

urlpatterns = [
    url(r'^index$', IndexView.as_view(), name='index'),# 显示首页
    url(r'^goods/(?P<goods_id>\d+)$', DetailView.as_view(), name='detail'),# 显示商品详情页
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list'), # 显示分类商品列表页
]

apps/order/urls.py
from django.conf.urls import url
from order.views import PlaceOrderView, OrderCommitView, OrderPayView, PayCheckView


urlpatterns = [
    url(r'^place$', PlaceOrderView.as_view(), name='place'), # 提交订单页面显示
    url(r'^commit$', OrderCommitView.as_view(), name='commit'), # 提交订单处理，生成订单
    url(r'^pay$', OrderPayView.as_view(), name='pay'), # 订单交易处理
    url(r'^pay/check$', PayCheckView.as_view(), name='pay_check'), # 订单支付结果查询
]

apps/user/urls.py
from django.conf.urls import url
from . import views
from user.views import RegisterView, ActiveView, LoginView, LogoutView, UserInfoView, UserAddressView, UserOrderView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # url(r'^register$', views.register, name='register'),# 注册
    url(r'^register$', RegisterView.as_view(), name='register'), # 注册
    url(r'^active/(?P<token>.*)$', ActiveView.as_view(), name='active'), #用户激活
    url(r'^login$', LoginView.as_view(), name='login'), # 登陆
    # url(r'^$', login_required(UserInfoView.as_view()), name='user_info'), # 用户中心-信息页
    # url(r'^order$', login_required(UserOrderView.as_view()), name='user_order'), # 用户中心-订单页
    # url(r'^address$', login_required(UserAddressView.as_view()), name='user_address'), # 用户中心-地址页

    url(r'^logout$', LogoutView.as_view(), name='logout'), # 退出登录
    url(r'^$', UserInfoView.as_view(), name='user_info'),  # 用户中心-信息页
    url(r'^order/(?P<page>\d+)$', UserOrderView.as_view(), name='user_order'), # 用户中心-订单页
    url(r'^address$', UserAddressView.as_view(), name='user_address'), # 用户中心-地址页
]

df_test/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),# django2.0：admin.site.urls可以不用include（）
    url(r'^tinymce/', include('tinymce.urls')),# 富文本编辑器
    url(r'^search$', include('haystack.urls')), # 全文检索框架
    url(r'^user/', include('user.urls', namespace='user')), # 用户模块
    url(r'^cart/', include('cart.urls', namespace='cart')), # 购物车模块
    url(r'^order/', include('order.urls', namespace='order')), # 订单模块
    url(r'^', include('goods.urls', namespace='goods')), # 商品模块
]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from goods.models import GoodsSKU
from django_redis import get_redis_connection
from utils.mixin import LoginRequiredMixin
# Create your views here.

# 用户添加商品到购物车分析
# 购物车数据记录：redis缓存--->hash--->cart_user.id: sku_id sku_count
# 请求方式：get--->获取信息，post--->增删改信息
# 点击添加购物车按钮，部分更新页面-->异步操作-->ajax请求-->返回json数据，应答采用JsonResponse
# url:/addcart----->需传递的参数2个：sku_id sku_count，采用post传参数
# 参数传递3种方式：1.url捕获, 2.get:/index?xx=xx, 3.post传递

# ajax发起的请求都在后台，在浏览器上看不到效果---->所以添加购物车视图类不能使用继承LoginRequiredMixin


# /cart/add
class AddCartView(View):
    """添加购物车类"""
    def post(self, request):
        '''添加购物车'''
        # 获取当前用户信息
        user = request.user
        # 首先判断用户是否已登陆
        if not user.is_authenticated():
            # 用户未登陆
            return JsonResponse({'res': 0, 'errmsg': '用户未登陆'})

        # 获取数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 校验数据
        # 1.校验数据是否完整
        if not all([sku_id, count]):
            # 数据不完整
            return JsonResponse({'res':1, 'errmsg':'数据不完整'})

        # 2.校验商品id是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品id不存在
            return JsonResponse({'res':2, 'errmsg':'商品id不存在'})

        # 3.校验count是否合法-->非数字，非空
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res':3, 'errmsg':'count不合法'})

        # 4.校验count是否负数
        if count < 0:
            return JsonResponse({'res':4, 'errmsg':'count非负数'})

        # 进行业务处理：添加购物车
        # 连接redis
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        # 判断该商品是否已经加入过购物车
        # 如果没有所要取的值,hget()会返回None
        sku_count = conn.hget(cart_key, sku_id)
        if sku_count:
            # 购物车中已经有该商品
            count += int(sku_count)

        # 校验商品的库存
        if count > sku.stock:
            # 库存不足
            return JsonResponse({'res':5, 'errmsg': '库存不足'})

        # 更新购物车商品数量
        conn.hset(cart_key, sku_id, count)
        # 返回购物车商品条目数--->页面右上角购物车显示
        cart_goods_count = conn.hlen(cart_key)

        # 返回应答
        return JsonResponse({'res':6, 'cart_goods_count':cart_goods_count,'sucess':'加入购物车成功'})


# /cart
class CartView(LoginRequiredMixin, View):
    """购物车页面"""
    def get(self, request):
        """显示购物车页面"""
        # 获取当前用户信息
        user = request.user
        # 获取购物车商品信息
        # 连接数据库
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id

        # 初始化
        skus = []
        total_count = 0
        total_amount = 0
        # 校验当前用户购物车是否为空--->若缓存中没有当前用户购物车记录，hlen()返回0，不会报错
        cart_goods_count = conn.hlen(cart_key)

        # cart_info_dict{商品id：商品数量}
        cart_info_dict = conn.hgetall(cart_key)
        print(cart_info_dict)

        for sku_id, count in cart_info_dict.items():

            sku = GoodsSKU.objects.get(id=int(sku_id))
            count = conn.hget(cart_key, sku_id)
            print(sku)
            # 给sku动态添加属性count--商品数量；商品小计amount
            sku.count = int(count)
            sku.amount = (sku.count)*(sku.price)
            skus.append(sku)
            total_count += sku.count
            total_amount += sku.amount

        context = {'skus': skus, 'total_count': total_count, 'total_amount': total_amount}

        return render(request, 'cart.html', context)


# 购物车商品数量增加或减少--->页面部分更新
# ajax post请求
# 需传递参数：sku_id count
# /cart/update
class UpdateCartView(View):
    """购物车页面更新"""
    def post(self,request):
        """更新购物车页面"""
        # 校验登陆
        user = request.user
        if not user.is_authenticated():
            # 用户未登陆
            return JsonResponse({'res':0, 'errmsg':'请先登陆'})
        # 获取传递的参数
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        # 校验数据
        # 1.校验数据完整性
        if not all([sku_id, count]):
            return JsonResponse({'res':1, 'errmsg':'数据不完整'})
        # 2.校验商品id是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品id不存在
            return JsonResponse({'res': 2, 'errmsg': '商品id不存在'})

        # 3.校验count是否合法-->非数字，非空
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 3, 'errmsg': 'count不合法'})

        # 4.校验count是否负数
        if count < 0:
            return JsonResponse({'res': 4, 'errmsg': 'count非负数'})

        # 进行业务处理：更新redis购物车记录
        # 连接redis
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id

        # 校验商品的库存
        if count > sku.stock:
            # 库存不足
            return JsonResponse({'res': 5, 'errmsg': '库存不足'})

        # 更新购物车记录
        conn.hset(cart_key, sku_id, count)

        # 计算购物车中所有的商品总数量
        total_count = 0
        # hvals可以返回所有的count值的列表
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)
        # 返回应答
        return JsonResponse({'res': 6, 'total_count': total_count, 'sucess': '更新购物车记录成功'})

# 从购物车中删除商品
# redis删除数据--hdel()
# ajax post
# sku_id
# /cart/del
class DelCartView(View):
    """从购物车中删除商品"""
    def post(self, request):
        """从购物车中删除商品"""
        # 校验登陆
        user = request.user
        if not user.is_authenticated():
            # 用户未登陆
            return JsonResponse({'res': 0, 'errmsg': '请先登陆'})
        # 获取传递的参数
        sku_id = request.POST.get('sku_id')

        # 校验数据
        # 校验数据完整
        if not sku_id:
            return JsonResponse({'res': 1, 'errmsg': '无效的商品id'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品id不存在
            return JsonResponse({'res': 2, 'errmsg': '商品id不存在'})

        # 进行业务处理：删除商品信息
        # 连接redis
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        conn.hdel(cart_key, sku_id)

        # 更新购物车商品总数量
        total_count = 0
        # hvals可以返回所有的count值的列表
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)
        # 返回应答
        return JsonResponse({'res': 3, 'total_count': total_count, 'sucess': '更新购物车记录成功'})

templates/base.html
{# 首页、注册、登陆页面 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>
        {# 文件标题块 #}
        {% block title %} {% endblock title %}
    </title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {# 顶部引入文件块 #}
    {% block topfiles %}{% endblock topfiles %}

</head>
<body>
        {# 顶部导航信息条块 #}
        {% block header_con %}
        <div class="header_con">
            <div class="header">
                <div class="welcome fl">欢迎来到天天生鲜!</div>
                <div class="fr">
                    {% if user.is_authenticated %}
                    <div class="login_btn fl">
                        欢迎您：<em>{{ user.username }}</em>
                        <span>|</span>
                        <a href="{% url 'user:logout' %}">退出</a>
                    </div>
                    {% else %}
                    <div class="login_btn fl">
                        <a href="{% url 'user:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'user:register' %}">注册</a>
                    </div>
                    {% endif %}
                    <div class="user_link fl">
                        <span>|</span>
                        <a href="{% url 'user:user_info' %}">用户中心</a>
                        <span>|</span>
                        <a href="{% url 'cart:cart' %}">我的购物车</a>
                        <span>|</span>
                        <a href="{% url 'user:user_order' 1 %}">我的订单</a>
                    </div>
                </div>
            </div>
        </div>
        {% endblock header_con %}

        {# 顶部搜索条块 #}
        {% block search_bar %}
        <div class="search_bar clearfix">
            <a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
            <div class="search_con fl">
                <form method="get" action="/search">
                    {% csrf_token %}
                    <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                    <input type="submit" class="input_btn fr" name="" value="搜索">
                </form>

            </div>
            <div class="guest_cart fr">
                <a href="{% url 'cart:cart' %}" class="cart_name fl">我的购物车</a>
                <div class="goods_count fl" id="show_count">{{cart_goods_count}}</div>
            </div>
        </div>
        {% endblock search_bar %}

        {# 页面主要内容块 #}
        {% block body %}
        {% endblock body %}

    <div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

    {# 网页底部html文件块 #}
    {% block bottom %}{% endblock bottom %}
    {# 网页底部引入文件块 #}
    {% block bottomfiles %}
    {% endblock bottomfiles %}

</body>
</html>

templates/base_detail_list.html
{# 详情页 列表页 #}
{% extends 'base.html' %}
{# 页面主要内容块 #}
    {% block body %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for type in types %}
					<li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">
                        {{ type.name }}</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
        {# 详情页、列表页主要内容块 #}
        {% block main_content %}{% endblock main_content %}
    {% endblock body %}

templates/base_user_center.html
{# 用户中心3页面 #}
{% extends 'base_no_cart.html' %}
{% block title %}天天生鲜-用户中心{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}
{# 页面主要内容块 #}
    {% block body %}
        <div class="main_con clearfix">
            <div class="left_menu_con clearfix">
                <h3>用户中心</h3>
                <ul>
                    <li><a href="{% url 'user:user_info' %}" {% if page_title = 'info' %}class="active"{% endif %}>· 个人信息</a></li>
                    <li><a href="{% url 'user:user_order' 1 %}" {% if page_title = 'order' %}class="active"{% endif %}>· 全部订单</a></li>
                    <li><a href="{% url 'user:user_address' %}" {% if page_title = 'address' %}class="active"{% endif %}>· 收货地址</a></li>
                </ul>
            </div>
            {# 页面右侧主要内容块 #}
            {% block right_content %}{% endblock right_content %}
        </div>
    {% endblock body %}

templates/detail.html
{% extends 'base_detail_list.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-商品详情{% endblock title %}


{% block main_content %}
    <div class="breadcrumb">
		<a href="{% url 'goods:index' %}">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' sku.type.id 1 %}">{{ sku.type }}</a>
		<span>></span>
		<a href="{% url 'goods:detail' sku.id %}">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ sku.image.url }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ sku.name }}</h3>
			<p>{{ sku.desc }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ sku.price }}</em></span>
				<span class="show_unit">单  位：{{ sku.unit }}</span>

			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>
				</div>
			</div>
            <div>
                <ul>
                    <div>其他规格：</div>
                    {% for sku in same_spu_goods %}
                        <li><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
			<div class="total">总价：<em>{{ sku.price }}元</em></div>
			<div class="operate_btn">
                {% csrf_token %}
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" sku_id="{{ sku.id }}" class="add_cart" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for new_sku in new_skus %}
					<li>
						<a href="{%  url 'goods:detail' new_sku.id %} "><img src="{{ new_sku.image.url }}"></a>
						<h4><a href="{%  url 'goods:detail' new_sku.id %}">{{ new_sku.name }}</a></h4>
						<div class="prize">￥{{ new_sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
                    {% autoescape off %}
					<dd>{{ sku.goods.detail }}</dd>
                    {% endautoescape %}
				</dl>
			</div>

            <div class="tab_content">
				<dl>
					<dt>评论：</dt>
                    {% for order_sku in order_skus %}
					<dd>评论时间：{{ order_sku.update_time }}&nbsp;&nbsp;用户名：{{ order_sku.order.user.username }}</dd>
                    <dd>评论内容：{{ order_sku.comment }}</dd>
                    {% endfor %}
				</dl>
			</div>

		</div>
	</div>
{% endblock %}



{% block bottom %}
    <div class="add_jump"></div>
{% endblock bottom %}

{% block bottomfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/add_cart.js' %}"></script>
{% endblock bottomfiles %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-首页{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js'%}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}

{% block body %}
    <div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
			<li><a href="{% url 'goods:list' type.id 1 %}" id="model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
			{% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for goods_banner in goods_banners %}
				<li><a href="{% url 'goods:detail' goods_banner.sku.id %}"><img src="{{ goods_banner.image.url }}"
                                                                          alt="幻灯片"></a></li>
				{% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for banner in promotion_banners %}
			<a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>

    {%  for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for type_goods_title in type.goods_titles %}
				<a href="{% url 'goods:detail' type_goods_title.sku.id %}">{{ type_goods_title.sku.name }}</a>
                {% endfor %}
			</div>
			<a href="{% url 'goods:list' type.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
                {% for type_goods_banner in type.goods_banners %}
				<li>
					<h4><a href="{% url 'goods:detail' type_goods_banner.sku.id %}">{{ type_goods_banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' type_goods_banner.sku.id %}"><img src="{{ type_goods_banner.sku.image.url }}"></a>
					<div class="prize">¥ {{ type_goods_banner.sku.price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}


{% endblock body %}

{% block bottomfiles %}
 	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
{% endblock bottomfiles %}

templates/list.html
{% extends 'base_detail_list.html' %}
{% block title %}天天生鲜-商品列表{% endblock title%}

{% block main_content %}
    <div class="breadcrumb">
		<a href="{% url 'goods:index' %}">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' type.id 1 %}">{{ type.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for new_sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' new_sku.id %}"><img src="{{ new_sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' new_sku.id %}">{{ new_sku.name }}</a></h4>
						<div class="prize">￥{{ new_sku.price }}</div>
					</li>
                    {% endfor %}

				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id 1 %}"
                   {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=price"
                   {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=hot"
                 {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for sku in skus %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price }}/{{ sku.unit }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}

			</ul>

			<div class="pagenation">
                {% if skus_page.has_previous %}
				<a href="{% url 'goods:list' type.id skus_page.previous_page_number %}"><上一页</a>
                {% endif %}

                {% for page_index in pages %}
				    <a href="{%  url 'goods:list' type.id page_index %}?sort={{ sort }}"
                       {% if page_index == skus_page.number %}class="active"{% endif %}>{{ page_index }}</a>
                {% endfor %}

                {% if skus_page.has_next %}
				<a href="{%  url 'goods:list' type.id skus_page.next_page_number %}">下一页></a>
                {% endif %}
			</div>
		</div>
	</div>
{% endblock main_content %}




templates/user_center_info.html
{% extends 'base_user_center.html' %}
{% load staticfiles %}
{# 页面右侧主要内容块 #}
{% block right_content %}
    <div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user.username }}</li>
                            {% if address %}
							<li><span>联系方式：</span>{{ address.phone }}</li>
							<li><span>联系地址：</span>{{ address.addr }}</li>
                            {% else %}
                            <li><span>联系方式：</span></li>
							<li><span>联系地址：</span></li>
                            {% endif %}
						</ul>
				</div>

				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                {% for goods in goods_list %}
				<li>
					<a href="{% url 'goods:detail' goods.id %}"><img src="{{ goods.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' goods.id %}">{{ goods.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ goods.price }}</span>
						<span class="unit">{{ goods.price }}/{{ goods.unit }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% empty %}
                    暂无浏览记录
                {% endfor %}
			</ul>
		</div>
		</div>
{% endblock right_content %}
